### ISSUE TITLE
Error during cleanup on SMB drive

### ISSUE THREAD

**Issue by MP-ICT-Diensten** [gruijter/com.gruijter.insights2csv#13]
I get the following error in the log when cleanup is started.

```
2020-09-10 03:27:00 [err] uncaughtException! TypeError: Cannot read property '1' of null at /app.js:683:45 at Array.filter () at /app.js:682:30 at /node_modules/@marsaud/smb2/lib/tools/smb2-connection.js:153:8 at /node_modules/@marsaud/smb2/lib/api/readdir.js:85:15 at /node_modules/@marsaud/smb2/lib/api/readdir.js:65:7 at Object.07000000 (/node_modules/@marsaud/smb2/lib/tools/message.js:19:15) at Socket. (/node_modules/@marsaud/smb2/lib/tools/smb2-forge.js:71:31) at Socket.emit (events.js:311:20) at addChunk (_stream_readable.js:294:12)
2020-09-10 03:27:00 [log] Deleting old data on SMB```

**Comment by gruijter** [comment]
I will check it out. Thx 4 reporting !

**Comment by gruijter** [comment]
Please try the new version 3:
https://homey.app/en-gb/app/com.gruijter.insights2csv/Archive-Insights/test/

Reopen the issue if you still have this problem
