### ISSUE TITLE
Error due to unescaped character (probably the "  character)

### ISSUE THREAD

**Issue by MP-ICT-Diensten** [gruijter/com.gruijter.insights2csv#14]
I get an error about an unescaped character:

```
2020-09-10 03:21:27 [err] TypeError [ERR_UNESCAPED_CHARACTERS]: Request path contains unescaped characters at new ClientRequest (_http_client.js:148:13) at request (http.js:46:10) at /node_modules/athom-api/dist/index.js:1:333197 at new Promise () at new g (/node_modules/athom-api/dist/index.js:1:331953) at g (/node_modules/athom-api/dist/index.js:1:331800) at /node_modules/athom-api/dist/index.js:1:1272004 at x (/node_modules/athom-api/dist/index.js:1:346389) at Generator.u._invoke (/node_modules/athom-api/dist/index.js:1:346184) at Generator.e. [as next] (/node_modules/athom-api/dist/index.js:1:346568) { code: 'ERR_UNESCAPED_CHARACTERS' }
2020-09-10 03:21:23 [log] getting logs related to net.i-dev.betterlogic

```

Better logic characters:
![2020-09-10_16-02-27](https://user-images.githubusercontent.com/28575285/92741631-1c55c280-f37f-11ea-952a-333c8670d47a.png)

**Comment by gruijter** [comment]
Where do you see the error, and what exactly is the error?

**Comment by MP-ICT-Diensten** [comment]
Sorry,  it was in the first comment, but not visible for some reason.

Marco

**Comment by gruijter** [comment]
Ok, thx. Looks like an issue in the athom api itself. But I can maybe find a workaround (or have to wait until infinity before Athom fixes it 😣)

**Comment by MP-ICT-Diensten** [comment]
My quick fix for now is the renaming of the better logic variable in a name without the " "  in it, was only used in 2 flows.
