### ISSUE TITLE
Ever seen these errors?

### ISSUE THREAD

**Issue by MP-ICT-Diensten** [gruijter/com.gruijter.insights2csv#15]
Ever seen these kinds of errors?

```
2020-09-09 03:08:28 [log] com.ikea.tradfri.gateway_20200909T010727Z_last24Hours.zip has been saved to SMB2
2020-09-09 03:08:28 [log] 15 files zipped, 96679 total bytes
2020-09-09 03:08:17 [err] Insights data is corrupt for WK1-LMP-01 bij bank energy_power
2020-09-09 03:08:05 [err] Insights data is corrupt for TK0-KEU-01 Tuinkamer keuken energy_power
2020-09-09 03:07:54 [err] Insights data is corrupt for KK1-LMP-01 Tafel energy_power
2020-09-09 03:07:39 [err] Insights data is corrupt for KT2-LMP-01 links (buro) energy_power
2020-09-09 03:07:28 [err] Insights data is corrupt for KT2-LMP-02 rechts (kast) energy_power
2020-09-09 03:07:27 [log] getting logs related to com.ikea.tradfri.gateway
```

```
2020-09-09 03:13:27 [err] opening '/opt/user/manager/insights/31a0f194189fb2d59e1553e8d6e0fcec.rrd': No such file or directory: opening '/opt/user/manager/insights/31a0f194189fb2d59e1553e8d6e0fcec.rrd': No such file or directory at /node_modules/athom-api/dist/index.js:1:1180307 at runMicrotasks () at processTicksAndRejections (internal/process/task_queues.js:97:5) { name: "opening '/opt/user/manager/insights/31a0f194189fb2d59e1553e8d6e0fcec.rrd': No such file or directory", code: 500, cause: t { __athom_api_type: 'HomeyAPI.ManagerInsights.Error', code: 500, error: "opening '/opt/user/manager/insights/31a0f194189fb2d59e1553e8d6e0fcec.rrd': No such file or directory", error_description: "opening '/opt/user/manager/insights/31a0f194189fb2d59e1553e8d6e0fcec.rrd': No such file or directory", '$stack': undefined } }
2020-09-09 03:13:17 [err] Insights data is corrupt for KT2-TEMP-01 measure_pressure
2020-09-09 03:13:05 [err] Insights data is corrupt for KT2-TEMP-01 measure_temperature
2020-09-09 03:12:54 [err] Insights data is corrupt for WK1-RAAM-02 Links measure_battery
2020-09-09 03:12:39 [err] Insights data is corrupt for KT2-RAAM-02 Links measure_battery
2020-09-09 03:12:28 [err] Insights data is corrupt for ZL3-RAAM-01 measure_battery
2020-09-09 03:12:17 [err] Insights data is corrupt for KT2-RAAM-01 Rechts measure_battery
2020-09-09 03:12:05 [err] Insights data is corrupt for SK2-RAAM-01 Links measure_battery
2020-09-09 03:11:54 [err] Insights data is corrupt for SK2-RAAM-02 Rechts measure_battery
2020-09-09 03:11:38 [err] Insights data is corrupt for KT2-Cube measure_battery
2020-09-09 03:11:27 [err] Insights data is corrupt for KT2-Cube cube_measure_rotation
2020-09-09 03:11:26 [log] getting logs related to com.xiaomi-mi
```

**Comment by gruijter** [comment]
It means in Homey something is wrong with your insights data. Can be solved by deleting those insights from Homey and start with a fresh history 😉

**Comment by MP-ICT-Diensten** [comment]
Yeah. How to delete them?

I have had a complete restore 3 weeks ago with this Homey, after restore insights are cleaned and we start over I suspect. I have now cleared all insights and reset the Homey, tomorrow I will look if the errors are gone.

Delete all insights:  https://community.athom.com/t/homey-insights-and-backup-errors/26036/10?u=m_a_r_c_o
